# Generated by Django 3.2 on 2021-04-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='imageurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
