# Generated by Django 3.2 on 2021-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_cartquan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cartquan',
            field=models.IntegerField(default=0),
        ),
    ]
